# Generated by Django 4.2.6 on 2024-02-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="ФИО клиента")),
                (
                    "phone_number",
                    models.CharField(max_length=14, verbose_name="Номер телефона"),
                ),
                (
                    "contract",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="№ договора"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="ФИО")),
                (
                    "phone_number",
                    models.CharField(max_length=14, verbose_name="Номер телефона"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(verbose_name="Количество сделок"),
                ),
            ],
            options={
                "verbose_name": "Менеджер",
                "verbose_name_plural": "Менеджеры",
            },
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Номер квартиры")),
                ("floor", models.PositiveIntegerField(verbose_name="Этаж")),
                ("square", models.PositiveIntegerField(verbose_name="Площадь")),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Активна", "Активна"),
                            ("Бронь", "Бронь"),
                            ("Куплено", "Куплено"),
                            ("Рассрочка", "Рассрочка"),
                            ("Бартер", "Бартер"),
                        ],
                        default="Активна",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "date_status",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата статуса"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.city",
                        verbose_name="Обьект",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Квартира",
                "verbose_name_plural": "Квартиры",
            },
        ),
    ]
