# Generated by Django 4.2.6 on 2024-02-01 19:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="backend.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="square",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Площадь",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
    ]
